# Generated by Django 6.0 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duracion', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
            ],
        ),
    ]
